# Generated by Django 5.0.6 on 2024-07-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='titale',
            new_name='title',
        ),
    ]
