# Generated by Django 5.0.6 on 2024-07-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newscategory_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views_qty',
            field=models.IntegerField(default=0),
        ),
    ]
