# Generated by Django 5.0.6 on 2024-07-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
