# Generated by Django 5.0.6 on 2024-07-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_product_user_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('social_link', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('user', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user_views',
            new_name='costumer_views',
        ),
    ]
