# Generated by Django 5.0.6 on 2024-07-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_profile_bio_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='costumer_views',
            new_name='customer_views',
        ),
    ]
