# Generated by Django 5.0.6 on 2024-07-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_rename_costumer_views_product_customer_views'),
        ('customer', '0002_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer_views',
            field=models.ManyToManyField(blank=True, to='customer.customer'),
        ),
    ]
