# Generated by Django 5.0.6 on 2024-07-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_rename_quarantee_product_guarantee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='photo'),
        ),
    ]
